<a href="https://colab.research.google.com/github/charliet28289/charliet28289/blob/main/Summer2026PythonDataProject1_Edit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Global E-Commerce Dataset - Kaggle (2025)

Source of Dataset:
https://www.kaggle.com/datasets/kojibrand/global-e-commerce-sales-dataset-2025?select=global_ecommerce_sales.csv

Step 1: Import Data Set into Colab

Install kagglehub package to connect the Kaggle API - More info: https://github.com/Kaggle/kagglehub/blob/main/README.md#download-dataset

In [ ]:
# pip install kagglehub

import kagglehub

In [ ]:
%env SummerProject2026=KGAT_7e92939fc0177057a06a74ba55eea388

env: SummerProject2026=KGAT_7e92939fc0177057a06a74ba55eea388

In [ ]:
# Download latest version
path = kagglehub.dataset_download("kojibrand/global-e-commerce-sales-dataset-2025")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/kojibrand/global-e-commerce-sales-dataset-2025/1.archive...

100%|██████████| 17.7k/17.7k [00:00<00:00, 28.4MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/kojibrand/global-e-commerce-sales-dataset-2025/versions/1

In [ ]:
kagglehub.dataset_download('kojibrand/global-e-commerce-sales-dataset-2025', path='global_ecommerce_sales.csv')

Using Colab cache for faster access to the 'global-e-commerce-sales-dataset-2025' dataset.

'/kaggle/input/global-e-commerce-sales-dataset-2025/global_ecommerce_sales.csv'

In [ ]:
from kagglehub import KaggleDatasetAdapter

# Load a DataFrame with a specific version of a CSV
df = kagglehub.dataset_load(KaggleDatasetAdapter.PANDAS,"kojibrand/global-e-commerce-sales-dataset-2025","global_ecommerce_sales.csv",)

Using Colab cache for faster access to the 'global-e-commerce-sales-dataset-2025' dataset.

In [ ]:
# confirming proper movement of the data

import pandas as pd

# data = pd.read_csv('global-ecommerce-sales-dataset-2025/global_ecommerce_sales.csv')
df.head()
# df.tail(10)

,Order_ID,Country,Category,Unit_Price,Quantity,Order_Date,Total_Amount
0,1,Germany,Electronics,285.82,7,6/12/2025,2000.74
1,2,Pakistan,Toys,132.00,9,1/14/2025,1188.00
2,3,Australia,Fashion,481.65,9,8/27/2025,4334.85
3,4,UAE,Grocery,244.36,3,3/13/2025,733.08
4,5,Germany,Sports,403.97,5,5/23/2025,2019.85

Step 2: Beginner Data Exploration

In [ ]:
df.info() # data types present: integer, floats, objects

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Order_ID      1200 non-null   int64
 1   Country       1200 non-null   object
 2   Category      1200 non-null   object
 3   Unit_Price    1200 non-null   float64
 4   Quantity      1200 non-null   int64
 5   Order_Date    1200 non-null   object
 6   Total_Amount  1200 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 65.8+ KB

In [ ]:
df.describe()
df.shape # (1200 rows, 7 columns)

(1200, 7)

In [ ]:
# Null Check
# pd.isnull(df)
# pd.notnull(df)

# Duplicate Check --How to

,Order_ID,Country,Category,Unit_Price,Quantity,Order_Date,Total_Amount
0,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...
1195,True,True,True,True,True,True,True
1196,True,True,True,True,True,True,True
1197,True,True,True,True,True,True,True
1198,True,True,True,True,True,True,True
1199,True,True,True,True,True,True,True

In [ ]:
# .unique vs. .nunique -- number vs. values

df['Category'].unique()
# 'Electronics', 'Toys', 'Fashion', 'Grocery', 'Sports', 'Home Decor', 'Beauty', 'Books'

# df['Category'].nunique()
# 8 unique catergories

df['Country'].unique()
#'Germany','Pakistan', 'Australia', 'UAE', 'Brazil', 'India', 'Canada', 'UK', 'USA', 'China'

# df['Country'].nunique()
# 10 unique countries

array(['Germany', 'Pakistan', 'Australia', 'UAE', 'Brazil', 'India',
       'Canada', 'UK', 'USA', 'China'], dtype=object)

In [ ]:
#Min/Max/Mean Across, Order Date, Unit Price and Total Amount

# df['Order_Date'].min() # 1/1/2025
# df['Order_Date'].max() # 9/8/2025

# df['Unit_Price'].min() # 5.07
# df['Unit_Price'].max() # 499.18
# df['Unit_Price'].mean() # 251.66
# df['Unit_Price'].median() # 252.76

# df['Total_Amount'].min() # 11.14
# df['Total_Amount'].max() # 4483.71
# df['Total_Amount'].mean() # 1260.21
# df['Total_Amount'].median() # 950.42

## df['Unit_Price'].min() # 5.07
## df['Unit_Price'].max() # 499.18
## df['Unit_Price'].mean() # 499.18
## df['Unit_Price'].mean() # 499.18

950.4200000000001

In [ ]:
df['Country'].value_counts() # orders per Country

Country
USA          143
India        130
UAE          127
Brazil       123
Australia    120
Germany      118
Canada       116
Pakistan     111
China        108
UK           104
Name: count, dtype: int64

In [ ]:
df['Category'].value_counts() #orders per Category

Category
Home Decor     161
Fashion        160
Electronics    154
Grocery        149
Beauty         148
Sports         147
Toys           145
Books          136
Name: count, dtype: int64

Manipulation ideas - Total X Country, Total X Category (both), change in order patterns over time - 3 quarters availble, sales trend over time per country-- difference between countries around holidays? weather patterns?

unique id = order id,

KPIs-- revenue growth rate, average order value (amount spent per order), average revenue per user -- per quarter,

In [ ]:
# # df.groupby('Country').sum('Total_Amount')

df.groupby('Country').sum('Total_Amount')

           Order_ID  Unit_Price  Quantity  Total_Amount
Country
Australia     72793    29863.99       610     151043.18
Brazil        71988    31100.59       624     162245.30
Canada        74723    25681.48       531     112635.93
China         62144    27397.14       531     134425.70
Germany       68704    32003.15       598     165844.33
India         76346    31411.69       653     152189.20
Pakistan      65988    26817.95       520     131479.73
UAE           77239    33537.97       705     185632.17
UK            65375    24462.82       513     110639.91
USA           85300    39715.49       723     206117.53

In [ ]:
df[df.Country == 'USA'] # 143 values

,Order_ID,Country,Category,Unit_Price,Quantity,Order_Date,Total_Amount
21,22,USA,Fashion,141.03,4,2/28/2025,564.12
25,26,USA,Home Decor,52.29,1,9/6/2025,52.29
51,52,USA,Books,56.53,7,7/13/2025,395.71
78,79,USA,Fashion,235.28,4,1/4/2025,941.12
83,84,USA,Books,346.55,2,5/26/2025,693.10
...,...,...,...,...,...,...,...
1148,1149,USA,Sports,267.81,8,6/20/2025,2142.48
1168,1169,USA,Grocery,387.71,8,5/9/2025,3101.68
1172,1173,USA,Sports,5.67,5,7/30/2025,28.35
1175,1176,USA,Books,487.23,7,10/6/2025,3410.61
1198,1199,USA,Books,186.01,1,3/8/2025,186.01

In [ ]:
df[df.Category == 'USA']